sudo: false
language: node_js
node_js:
  - "node"
os:
  - osx
  - linux
dist: xenial

before_install:
  - cd src

addons:
  homebrew:
    packages:
      - wine

  apt:
    packages:
      - xvfb
      - wine

install:
  - npm i
  - npm i electron-packager

#nbefore_script:
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  #- sleep 3 # give xvfb some time to start
script:
  - echo $PATH
  - npm test
  - npm run build
  - codecov

env:
  global:
    # prevent wine popup dialogs about installing additional packages
    - WINEDLLOVERRIDES="mscoree,mshtml="
    - WINEDEBUG="-all"
